DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS NOTES;

CREATE TABLE USERS (
  ID       INTEGER     NOT NULL AUTO_INCREMENT UNIQUE,
  NAME     VARCHAR(50),
  LOGIN    VARCHAR(50) NOT NULL UNIQUE,
  PASSWORD VARCHAR(50) NOT NULL,
  ROLE     VARCHAR(10) NOT NULL,

  PRIMARY KEY (ID)
);

CREATE TABLE NOTES (
  ID      INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
  NAME    VARCHAR(50),
  TEXT    VARCHAR(50),
  DATE    date,

  USER_ID INTEGER NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

INSERT INTO USERS (NAME, LOGIN, PASSWORD, ROLE)
VALUES ('TomUser', 'user', 'user', 'USER');

INSERT INTO USERS (NAME, LOGIN, PASSWORD, ROLE)
VALUES ('AdminName', 'admin', 'admin', 'ADMIN');

INSERT INTO NOTES (NAME, TEXT, DATE, USER_ID)
VALUES ('toy', 'mrrr', '2018-05-06', 1);
INSERT INTO NOTES (NAME, TEXT, DATE, USER_ID)
VALUES ('rik', 'eeer', '2018-06-05', 1);
INSERT INTO NOTES (NAME, TEXT, DATE, USER_ID)
VALUES ('mila', 'fg', '2018-05-06', 1);
INSERT INTO NOTES (NAME, TEXT, DATE, USER_ID)
VALUES ('roy', 'rr', '2018-05-06', 1);
INSERT INTO NOTES (NAME, TEXT, DATE, USER_ID)
VALUES ('rflg', 'rr', '2018-05-06', 1);
INSERT INTO NOTES (NAME, TEXT, DATE, USER_ID)
VALUES ('ry', 'rr', '2018-05-06', 1);