DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS NOTE;

CREATE TABLE USERS(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME   VARCHAR(50),
  LOGIN   VARCHAR(50),
  PASSWORD  VARCHAR(50),
  ROLE VARCHAR (10),

  PRIMARY KEY (ID)
);

CREATE TABLE NOTE (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME   VARCHAR(50),
  TEXT   VARCHAR(50),
  DATE date ,

  USER_ID INTEGER,

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

INSERT INTO USERS(NAME, LOGIN, PASSWORD, ROLE)VALUES ('TomUser','user','user','USER');

INSERT INTO NOTE(NAME, TEXT, DATE)VALUES ('toy','mrrr','2018-05-06');